apiVersion: apps/v1
kind: Deployment
metadata:
  name: ben-knox-dot-com
spec:
  selector:
    matchLabels:
      app: ben-knox-dot-com
  replicas: 1
  template:
    metadata:
      labels:
        app: ben-knox-dot-com
    spec:
      containers:
        - name: ben-knox-dot-com
          envFrom:
          - secretRef:
              name: ben-knox-dot-com-env
          image: ghcr.io/benjaminknox/ben-knox-dot-com:7da9000
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ben-knox-dot-com-service
spec:
  selector:
    app: ben-knox-dot-com
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ben-knox-dot-com-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
  - hosts:
    - ben-knox.com.local
    secretName: ben-knox-dot-com-local-tls-secret
  rules:
    - host: "ben-knox.com.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ben-knox-dot-com-service
                port:
                  number: 3000
